# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bd21be2f-d529-4073-941a-85a9526265eb";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/bd21be2f-d529-4073-941a-85a9526265eb";
      fsType = "btrfs";
      options = [ "subvol=@nixos-nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/bd21be2f-d529-4073-941a-85a9526265eb";
      fsType = "btrfs";
      options = [ "subvol=@nixos-home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5627-93D9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/023a962b-4822-4013-91b3-986043565d33"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
